CONFIG_GPIO=y
# enable c++ support
CONFIG_CPP=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_FPU=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETLINE=y

# Logging
#CONFIG_LOG=y
#CONFIG_ASSERT=y
#CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024

# Edge Impulse SDK
CONFIG_EDGE_IMPULSE_SDK=y

# Camera support configuration
CONFIG_VIDEO=y

CONFIG_DMA=y

# capture format
#CONFIG_VIDEO_PIXEL_FORMAT="RGBP"
# config if you need to locate the video buffer pool in a specific memory region
# ie for esp32s3-eyes use the external ram

