CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=230400
CONFIG_ESP_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_VIDEO_BUFFER_POOL_ALIGN=32
CONFIG_DMA_ESP32_MAX_DESCRIPTOR_NUM=64
CONFIG_VIDEO_BUFFER_USE_SHARED_MULTI_HEAP=y
CONFIG_VIDEO_BUFFER_SMH_ATTRIBUTE=2
CONFIG_VIDEO_FRAME_HEIGHT=240
CONFIG_VIDEO_FRAME_WIDTH=240
CONFIG_VIDEO_PIXEL_FORMAT="RGBP"

# Heap size allocated in SPIRAM
#CONFIG_ESP_SPIRAM_HEAP_SIZE=2097152

# manually allocate video buffers in SPIRAM section
CONFIG_VIDEO_BUFFER_POOL_ZEPHYR_REGION=y
CONFIG_VIDEO_BUFFER_POOL_ZEPHYR_REGION_NAME=".ext_ram.bss"
#CONFIG_INFERENCE_BUFFER_USE_SECTION=y
#CONFIG_INFERENCE_BUFFER_SECTION_NAME=".ext_ram.bss"
# use shared heap for ei_malloc/ei_free
#CONFIG_USE_SHARED_MULTI_HEAP=y
#CONFIG_USE_EXTERNAL_HEAP=y
#CONFIG_USE_EXTERNAL_HEAP_SECTION_NAME=".ext_ram.bss"
#CONFIG_USE_EXTERNAL_HEAP_SIZE=196608

CONFIG_INFERENCE_BUFFER_USE_SECTION=y
CONFIG_INFERENCE_BUFFER_SECTION_NAME=".ext_ram.bss"
