CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=55296
CONFIG_ESP_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_VIDEO_BUFFER_POOL_ALIGN=32
CONFIG_DMA_ESP32_MAX_DESCRIPTOR_NUM=64
CONFIG_VIDEO_BUFFER_USE_SHARED_MULTI_HEAP=y
CONFIG_VIDEO_BUFFER_SMH_ATTRIBUTE=2
CONFIG_VIDEO_FRAME_HEIGHT=96
CONFIG_VIDEO_FRAME_WIDTH=96
CONFIG_VIDEO_PIXEL_FORMAT="RGBP"
CONFIG_VIDEO_BUFFER_POOL_ZEPHYR_REGION=y
CONFIG_VIDEO_BUFFER_POOL_ZEPHYR_REGION_NAME=".ext_ram.bss"

# Enable heap and place it in PSRAM for TensorFlow Lite arena  
CONFIG_HEAP_MEM_POOL_SIZE=2097152